modLoader = "lowcodefml"
loaderVersion = "${forge_loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''
${mod_description}
'''
logoFile="liosoverhauledvillageslogo.png"
